# Generated by Django 3.2.9 on 2021-11-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(help_text='ex : Boeing 777', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ex : aéroport Charles de Gaulle', max_length=100)),
                ('code', models.CharField(help_text='ex : CDG', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='ex : Marc', max_length=100)),
                ('last_name', models.CharField(help_text='ex : Cohen', max_length=100)),
                ('adress', models.CharField(help_text='ex : 16 rue de la paix, 75000 Paris', max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('security_number', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_airport_id', models.IntegerField()),
                ('arrival_airport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Marcair.airport')),
            ],
        ),
    ]
