# Generated by Django 3.2.9 on 2021-11-22 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0002_auto_20211122_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='ex : Pierre', max_length=100)),
                ('last_name', models.CharField(help_text='ex : Niney', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(help_text='ex : Stewart, Hotesse', max_length=30)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew', to='Marcair.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_empty_seat', models.PositiveIntegerField()),
                ('number_of_reserved_seat', models.PositiveIntegerField()),
                ('first_crew_member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew1', to='Marcair.crewmember')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.PositiveIntegerField(unique=True)),
                ('date_time_of_issue', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_ticket', to='Marcair.client')),
                ('departure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_ticket', to='Marcair.departure')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_number', models.PositiveIntegerField(unique=True)),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_transaction', to='Marcair.client')),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transaction', to='Marcair.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.PositiveIntegerField(unique=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot', to='Marcair.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('flight_number', models.PositiveIntegerField(unique=True)),
                ('departure_day', models.DateField()),
                ('arrival_day', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('airplane_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airplane_flight', to='Marcair.airplane')),
                ('connection_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_flight', to='Marcair.connection')),
            ],
        ),
        migrations.AddField(
            model_name='departure',
            name='flight_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_departure', to='Marcair.flight'),
        ),
        migrations.AddField(
            model_name='departure',
            name='optional_pilot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot', to='Marcair.pilot'),
        ),
        migrations.AddField(
            model_name='departure',
            name='pilot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_departure', to='Marcair.pilot'),
        ),
        migrations.AddField(
            model_name='departure',
            name='second_crew_member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew2', to='Marcair.crewmember'),
        ),
    ]
