# Generated by Django 3.2.9 on 2021-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0005_auto_20211123_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, unique=True)),
                ('pourcentage', models.FloatField(default=0)),
            ],
        ),
    ]
