# Generated by Django 3.2.9 on 2021-11-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0006_reduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reduction',
        ),
    ]
