# Generated by Django 3.2.9 on 2021-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0007_delete_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(default='France', help_text='ex : France', max_length=100),
            preserve_default=False,
        ),
    ]
