# Generated by Django 3.2.9 on 2021-12-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0009_client_client_email_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
