# Generated by Django 3.2.9 on 2021-12-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0010_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Marcair.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_transaction', to='Marcair.client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_transaction', to='Marcair.ticket'),
        ),
    ]
