# Generated by Django 3.2.9 on 2021-12-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0011_auto_20211205_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(default='Employees', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_id', to='Marcair.departure'),
        ),
    ]
