# Generated by Django 3.2.9 on 2021-12-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0012_auto_20211205_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='second_crew_member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew2', to='Marcair.crewmember'),
        ),
    ]
