# Generated by Django 3.2.9 on 2021-12-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0014_auto_20211206_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
