# Generated by Django 3.2.9 on 2021-12-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0015_auto_20211207_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='departures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival', to='Marcair.connection'),
        ),
    ]
