# Generated by Django 3.2.9 on 2021-12-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0016_airport_departures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='departures',
        ),
    ]
