# Generated by Django 3.2.9 on 2021-11-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcair', '0003_auto_20211122_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_date',
        ),
    ]
